In [43]:
# Import
from pathlib import Path
from bs4 import BeautifulSoup
import pandas as pd
import requests
#import ipywidgets as widgets
#from ipywidgets import interact

In [44]:
# Read CSV
sp500_csv = Path("Resources/sp500.csv")
sp500 = pd.read_csv(sp500_csv)
sp500.head()

  Symbol                 Name       Sector
0    MMM           3M Company  Industrials
1    AOS      A.O. Smith Corp  Industrials
2    ABT  Abbott Laboratories  Health Care
3   ABBV          AbbVie Inc.  Health Care
4   ABMD          ABIOMED Inc  Health Care

In [52]:
# Create DataFrame and ESG column
ticker_list = sp500['Symbol']
ticker_list_df = pd.DataFrame(ticker_list)
ticker_list_df["ESG Score"] = 0
ticker_list_df.head()

  Symbol  ESG Score
0    MMM          0
1    AOS          0
2    ABT          0
3   ABBV          0
4   ABMD          0

In [53]:
# for loop for ESG score to symbol
for ticker in ticker_list:
    url_symbol = 'https://finance.yahoo.com/quote/' + ticker + '/sustainability?p=' + ticker
    try:
        web_data = requests.get(url_symbol).text
        soup = BeautifulSoup(web_data, 'html.parser')
        esg_score = soup.find('div',{'class': 'Fz(36px) Fw(600) D(ib) Mend(5px)'})
        datapoint = esg_score.text
        ticker_list_df["ESG Score"][ticker_list_df.Symbol==ticker] = int(datapoint)
    except:
        ticker_list_df["ESG Score"][ticker_list_df.Symbol==ticker] = None
    print(ticker)

C:\Users\palex\.conda\envs\pyvizenv\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

MMM
AOS
ABT
ABBV

C:\Users\palex\.conda\envs\pyvizenv\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.

ABMD
ACN
ATVI
ADBE
AAP
AMD
AES
AFL
A
APD
AKAM
ALK
ALB
ARE
ALXN
ALGN
ALLE
LNT
ALL
GOOGL
GOOG
MO
AMZN
AMCR
AEE
AAL
AEP
AXP
AIG
AMT
AWK
AMP
ABC
AME
AMGN
APH
ADI
ANSS
ANTM
AON
APA
AIV
AAPL
AMAT
APTV
ADM
ANET
AJG
AIZ
T
ATO
ADSK
ADP
AZO
AVB
AVY
BKR
BLL
BAC
BAX
BDX
BRK.B
BBY
BIO
BIIB
BLK
BA
BKNG
BWA
BXP
BSX
BMY
AVGO
BR
BF.B
CHRW
COG
CDNS
CPB
COF
CAH
KMX
CCL
CARR
CAT
CBOE
CBRE
CDW
CE
CNC
CNP
CTL
CERN
CF
SCHW
CHTR
CVX
CMG
CB
CHD
CI
CINF
CTAS
CSCO
C
CFG
CTXS
CME
CMS
KO
CTSH
CL
CMCSA
CMA
CAG
CXO
COP
ED
STZ
CPRT
GLW
CTVA
COST
COTY
CCI
CSX
CMI
CVS
DHI
DHR
DRI
DVA
DE
DAL
XRAY
DVN
DXCM
FANG
DLR
DFS
DISCA
DISCK
DISH
DG
DLTR
D
DPZ
DOV
DOW
DTE
DUK
DRE
DD
DXC
ETFC
EMN
ETN
EBAY
ECL
EIX
EW
EA
EMR
ETR
EOG
EFX
EQIX
EQR
ESS
EL
RE
EVRG
ES
EXC
EXPE
EXPD
EXR
XOM
FFIV
FB
FAST
FRT
FDX
FIS
FITB
FRC
FE
FISV
FLT
FLIR
FLS
FMC
F
FTNT
FTV
FBHS
FOXA
FOX
BEN
FCX
GPS
GRMN
IT
GD
GE
GIS
GM
GPC
GILD
GPN
GL
GS
GWW
HRB
HAL
HBI
HIG
HAS
HCA
PEAK
HSIC
HES
HPE
HLT
HFC
HOLX
HD
HON
HRL
HST
HWM
HPQ
HUM
HBAN
HII
IEX
IDXX
INFO
ITW
ILMN
INCY
IR
INTC
ICE
IBM
IFF
IP
IPG
INTU
ISRG
IVZ
IPGP
IQV
IRM
JBHT
JKHY
J
SJM
JNJ
JCI
JPM
JNPR
KSU
K
KEY
KEYS
KMB
KIM
KMI
KLAC
KSS
KHC
KR
LB
LHX
LH
LRCX
LW
LVS
LEG
LDOS
LEN
LLY
LNC
LIN
LYV
LKQ
LMT
L
LOW
LYB
MTB
MRO
MPC
MKTX
MAR
MMC
MLM
MAS
MA
MXIM
MKC
MCD
MCK
MDT
MRK
MET
MTD
MGM
MCHP
MU
MSFT
MAA
MHK
TAP
MDLZ
MNST
MCO
MS
MSI
MSCI
MYL
NDAQ
NOV
NTAP
NFLX
NWL
NEM
NWSA
NWS
NEE
NLSN
NKE
NI
NBL
NSC
NTRS
NOC
NLOK
NCLH
NRG
NUE
NVDA
NVR
ORLY
OXY
ODFL
OMC
OKE
ORCL
OTIS
PCAR
PKG
PH
PAYX
PAYC
PYPL
PNR
PBCT
PEP
PKI
PRGO
PFE
PM
PSX
PNW
PXD
PNC
PPG
PPL
PFG
PG
PGR
PLD
PRU
PEG
PSA
PHM
PVH
QRVO
QCOM
PWR
DGX
RL
RJF
RTX
O
REG
REGN
RF
RSG
RMD
RHI
ROK
ROL
ROP
ROST
RCL
SPGI
CRM
SBAC
SLB
STX
SEE
SRE
NOW
SHW
SPG
SWKS
SLG
SNA
SO
LUV
SWK
SBUX
STT
STE
SYK
SIVB
SYF
SNPS
SYY
TMUS
TROW
TTWO
TPR
TGT
TEL
FTI
TDY
TFX
TXN
TXT
BK
CLX
COO
HSY
MOS
TRV
DIS
TMO
TIF
TJX
TSCO
TT
TDG
TFC
TWTR
TYL
TSN
USB
UDR
ULTA
UAA
UA
UNP
UAL
UNH
UPS
URI
UHS
UNM
VLO
VAR
VTR
VRSN
VRSK
VZ
VRTX
VFC
VIAC
V
VNO
VMC
WRB
WAB
WBA
WMT
WM
WAT
WEC
WFC
WELL
WST
WDC
WU
WRK
WY
WHR
WMB
WLTW
WYNN
XEL
XRX
XLNX
XYL
YUM
ZBRA
ZBH
ZION
ZTS

TypeError: can only concatenate str (not "int") to str

In [57]:
ticker_list_df.to_csv('Resources/sp500_with_esg.csv')

  Symbol
0    MMM
1    AOS
2    ABT
3   ABBV
4   ABMD

AttributeError: 'DataFrame' object has no attribute 'typedf'